### ISSUE TITLE
今あるイメージデータをこのリポジトリに集約する

### ISSUE THREAD

**Issue by linyows** [fukuokago/resources#1]
これぐらいですかねー @keitakawamoto 

- [x] ラーメンGopherアイコン
- [x] にわかGopherアイコン
- [x] Gopherバナー
- [x] Gopherアクリル

**Comment by keitakawamoto** [comment]
すべて https://github.com/fukuokago/fukuoka.go/pull/2 で追加しました。

**Comment by linyows** [comment]
助かりまっす！！
